name: ecats
description: eCats

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_icons: ^2.0.2
  http: ^0.13.5
  flutter_model_form_validation: ^1.0.2
  flutter_secure_storage: ^7.0.1
  decimal: ^2.3.2
  dropdown_button2: ^1.9.2
  data_table_2: ^2.3.11
  intl: ^0.16.1
  split_view: ^3.2.1
  multi_split_view: ^2.2.0
  flutter_tab_indicator_styler: ^2.0.0
  input_quantity: ^1.1.4
  group_button: ^5.2.2
  signalr_client: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/logo.png
    - assets/google.png
    - assets/facebook.png

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Black.ttf
        - asset: fonts/Nunito/Nunito-BlackItalic.ttf
        - asset: fonts/Nunito/Nunito-Bold.ttf
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito/Nunito-ExtraLightItalic.ttf
        - asset: fonts/Nunito/Nunito-Italic.ttf
        - asset: fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
        - asset: fonts/Nunito/Nunito-Light.ttf
        - asset: fonts/Nunito/Nunito-LightItalic.ttf
        - asset: fonts/Nunito/Nunito-Medium.ttf
        - asset: fonts/Nunito/Nunito-MediumItalic.ttf
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
        - asset: fonts/Nunito/Nunito-SemiBoldItalic.ttf
        - asset: fonts/Nunito/Nunito-VariableFont_wght.ttf

  uses-material-design: true
