name: ecats
description: eCats

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_icons: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logo.png
    - assets/google.png
    - assets/facebook.png

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Black.ttf
        - asset: fonts/Nunito/Nunito-BlackItalic.ttf
        - asset: fonts/Nunito/Nunito-Bold.ttf
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito/Nunito-ExtraLightItalic.ttf
        - asset: fonts/Nunito/Nunito-Italic.ttf
        - asset: fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
        - asset: fonts/Nunito/Nunito-Light.ttf
        - asset: fonts/Nunito/Nunito-LightItalic.ttf
        - asset: fonts/Nunito/Nunito-Medium.ttf
        - asset: fonts/Nunito/Nunito-MediumItalic.ttf
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
        - asset: fonts/Nunito/Nunito-SemiBoldItalic.ttf
        - asset: fonts/Nunito/Nunito-VariableFont_wght.ttf

  uses-material-design: true
